esphome:
    name: exampled1mini # The name of the device
  
  esp8266: # The platform type
    board: d1_mini # The type of ESP board
    
  # Enabling the logging component
  logger:
  
  # Enable Home Assistant API
  api:
    encryption:
      key: "i51USvDruBRuPndxTYuQ41ijowUdoQVXOKYwPUQITAw=" # This is the HA encryption key HA asks for during the device discovery
      
  # The OTA flashing password
  ota:
    password: !secret ota_password
  
  wifi: # Your Wifi network details
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    
  # Enable fallback hotspot in case wifi connection fails  
    ap:
      ssid: "exampled1mini Fallback Hotspot" # The name of the AP the device will make
      password: !secret ap_password # The AP password
  captive_portal: